import type {
  InsertProfile,
  InsertSocialLink,
  InsertProject,
  InsertExperience,
  InsertSkill,
  InsertTestimonial,
} from "./schema";

export const initialProfile: InsertProfile = {
  id: 1,
  name: "Alex Vance",
  role: "Senior Full-Stack & Systems Engineer",
  headline: "Architecting resilient distributed backends and high-craft interfaces.",
  location: "San Francisco, CA • Open to Global Remote",
  availabilityStatus: "Open for high-impact roles & technical consulting",
  bio: "Senior engineer with 8+ years of experience designing fault-tolerant distributed systems, low-latency microservices, and bespoke web platforms. Obsessed with mechanical sympathy, zero-runtime overhead, and thoughtful user-centered craft.",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
  resumeUrl: "#",
  email: "alex.vance@example.dev",
  githubUrl: "https://github.com",
  updatedAt: Date.now(),
};

export const initialSocialLinks: InsertSocialLink[] = [
  {
    id: "soc-github",
    platform: "GitHub",
    url: "https://github.com",
    icon: "github",
    isActive: true,
    displayOrder: 1,
    createdAt: Date.now(),
  },
  {
    id: "soc-linkedin",
    platform: "LinkedIn",
    url: "https://linkedin.com",
    icon: "linkedin",
    isActive: true,
    displayOrder: 2,
    createdAt: Date.now(),
  },
  {
    id: "soc-twitter",
    platform: "X / Twitter",
    url: "https://x.com",
    icon: "twitter",
    isActive: true,
    displayOrder: 3,
    createdAt: Date.now(),
  },
  {
    id: "soc-instagram",
    platform: "Instagram",
    url: "https://instagram.com",
    icon: "instagram",
    isActive: true, // Only shown when active toggle is on!
    displayOrder: 4,
    createdAt: Date.now(),
  },
  {
    id: "soc-facebook",
    platform: "Facebook",
    url: "https://facebook.com",
    icon: "facebook",
    isActive: false, // Inactive by default to demonstrate the toggle switch
    displayOrder: 5,
    createdAt: Date.now(),
  },
  {
    id: "soc-discord",
    platform: "Discord",
    url: "https://discord.com",
    icon: "discord",
    isActive: false,
    displayOrder: 6,
    createdAt: Date.now(),
  },
];

export const initialProjects: InsertProject[] = [
  {
    id: "proj-kestrel",
    title: "Kestrel DB",
    slug: "kestrel-db",
    tagline: "High-throughput append-only event stream engine with sub-millisecond p99 latency.",
    description: "Designed a distributed event store in Go and Rust utilizing zero-copy IO ring buffers and LSM tree persistence. Outperformed conventional Kafka configurations by 3.2x under high contention.",
    impactMetric: "3.2x throughput over standard clusters · 0.8ms p99 latency",
    tags: JSON.stringify(["Go", "Rust", "Distributed Systems", "io_uring", "Zero-Copy"]),
    featured: true,
    displayOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&auto=format&fit=crop&q=80",
    repoUrl: "https://github.com",
    liveUrl: "https://github.com",
    createdAt: Date.now() - 100000,
  },
  {
    id: "proj-strata",
    title: "Strata Analytics",
    slug: "strata-analytics",
    tagline: "Real-time telemetry and edge analytics pipeline processing 40M+ daily events.",
    description: "Built the ingest edge gateways and interactive visualization dashboard using Next.js App Router, ClickHouse, and Bun. Features live WebSocket scrubbing and sub-second rollups.",
    impactMetric: "Processes 40M+ events/day · Sub-50ms analytics query time",
    tags: JSON.stringify(["Next.js", "TypeScript", "ClickHouse", "Bun", "WebSockets"]),
    featured: true,
    displayOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80",
    repoUrl: "https://github.com",
    liveUrl: "https://github.com",
    createdAt: Date.now() - 80000,
  },
  {
    id: "proj-hyperion",
    title: "Hyperion Edge Gateway",
    slug: "hyperion-edge-gateway",
    tagline: "Zero-trust service mesh router with automated TLS termination and dynamic rate limiting.",
    description: "Engineered an intelligent reverse proxy leveraging eBPF packet inspection and Redis token-bucket state. Reduced cold-start connection latency across 12 worldwide edge nodes.",
    impactMetric: "68% drop in edge handshake latency across 12 PoPs",
    tags: JSON.stringify(["eBPF", "Rust", "Redis", "Zero-Trust", "Docker"]),
    featured: true,
    displayOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&auto=format&fit=crop&q=80",
    repoUrl: "https://github.com",
    liveUrl: "https://github.com",
    createdAt: Date.now() - 60000,
  },
  {
    id: "proj-pulse-ui",
    title: "Pulse Design System",
    slug: "pulse-design-system",
    tagline: "Headless, accessible component primitives engineered for mission-critical interfaces.",
    description: "Created an internal design token architecture with WCAG AAA accessibility compliance, fluid micro-interactions, and zero layout shift.",
    impactMetric: "Adopted across 14 internal product suites",
    tags: JSON.stringify(["React", "Tailwind CSS", "Radix UI", "Accessibility"]),
    featured: false,
    displayOrder: 4,
    imageUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1200&auto=format&fit=crop&q=80",
    repoUrl: "https://github.com",
    liveUrl: "https://github.com",
    createdAt: Date.now() - 40000,
  },
];

export const initialExperiences: InsertExperience[] = [
  {
    id: "exp-1",
    role: "Staff Infrastructure Engineer",
    company: "Veloce Cloud Systems",
    companyUrl: "https://example.com",
    location: "San Francisco, CA",
    startDate: "2023",
    endDate: "Present",
    description: "Leading the Core Services infrastructure team. Spearheading distributed persistence, edge routing architecture, and developer productivity tooling.",
    highlights: JSON.stringify([
      "Architected multi-region failover protocol cutting disaster recovery RTO from 45 min to under 12 seconds.",
      "Mentored 12 engineers across backend systems and infrastructure divisions.",
      "Reduced AWS compute expenditure by $420k/yr via ARM64 migration and custom memory allocators.",
    ]),
    displayOrder: 1,
  },
  {
    id: "exp-2",
    role: "Senior Full-Stack Engineer",
    company: "Monolith Labs",
    companyUrl: "https://example.com",
    location: "New York, NY",
    startDate: "2020",
    endDate: "2023",
    description: "Owned high-throughput real-time financial telemetry dashboard and low-latency order execution pipelines.",
    highlights: JSON.stringify([
      "Rewrote legacy monolithic order engine into async event-driven services processing 15k req/sec.",
      "Built low-latency real-time charting library in WebGL and TypeScript.",
    ]),
    displayOrder: 2,
  },
  {
    id: "exp-3",
    role: "Software Engineer",
    company: "Prism Digital",
    companyUrl: "https://example.com",
    location: "Austin, TX",
    startDate: "2018",
    endDate: "2020",
    description: "Full-stack product engineer building SaaS applications, GraphQL APIs, and custom analytics pipelines.",
    highlights: JSON.stringify([
      "Designed and shipped 6 core web applications from zero to production.",
      "Achieved 99.98% uptime SLA across all client-facing APIs.",
    ]),
    displayOrder: 3,
  },
];

export const initialSkills: InsertSkill[] = [
  { id: "sk-1", name: "TypeScript / Node.js", category: "Languages & Core", level: "Expert", isHighlighted: true, displayOrder: 1 },
  { id: "sk-2", name: "Go (Golang)", category: "Languages & Core", level: "Expert", isHighlighted: true, displayOrder: 2 },
  { id: "sk-3", name: "Rust", category: "Languages & Core", level: "Proficient", isHighlighted: true, displayOrder: 3 },
  { id: "sk-4", name: "Python", category: "Languages & Core", level: "Proficient", isHighlighted: false, displayOrder: 4 },
  
  { id: "sk-5", name: "Next.js 15 (App Router)", category: "Frontend & UI", level: "Expert", isHighlighted: true, displayOrder: 5 },
  { id: "sk-6", name: "React 19 & RSC", category: "Frontend & UI", level: "Expert", isHighlighted: true, displayOrder: 6 },
  { id: "sk-7", name: "Tailwind CSS v4", category: "Frontend & UI", level: "Expert", isHighlighted: true, displayOrder: 7 },
  { id: "sk-8", name: "Motion & Animation", category: "Frontend & UI", level: "Proficient", isHighlighted: false, displayOrder: 8 },

  { id: "sk-9", name: "PostgreSQL & ClickHouse", category: "Storage & Databases", level: "Expert", isHighlighted: true, displayOrder: 9 },
  { id: "sk-10", name: "SQLite / LibSQL & Turso", category: "Storage & Databases", level: "Expert", isHighlighted: true, displayOrder: 10 },
  { id: "sk-11", name: "Redis & Memory Caches", category: "Storage & Databases", level: "Expert", isHighlighted: false, displayOrder: 11 },

  { id: "sk-12", name: "Docker & Kubernetes", category: "DevOps & Cloud", level: "Expert", isHighlighted: true, displayOrder: 12 },
  { id: "sk-13", name: "eBPF & Linux Internals", category: "DevOps & Cloud", level: "Proficient", isHighlighted: true, displayOrder: 13 },
  { id: "sk-14", name: "AWS & Cloudflare Edge", category: "DevOps & Cloud", level: "Expert", isHighlighted: false, displayOrder: 14 },
];

export const initialTestimonials: InsertTestimonial[] = [
  {
    id: "test-1",
    author: "Elena Rostova",
    role: "VP of Engineering",
    company: "Veloce Cloud",
    content: "Alex combines deep low-level systems knowledge with an unmatched eye for interface quality. Rare engineer who can debug Linux kernels in the morning and ship immaculate frontend code in the afternoon.",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80",
    displayOrder: 1,
  },
  {
    id: "test-2",
    author: "Marcus Chen",
    role: "Principal Architect",
    company: "Monolith Labs",
    content: "When our order ingestion pipeline hit critical limits, Alex redesigned the entire messaging fabric in three weeks. Reliability shot up to four nines immediately.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    displayOrder: 2,
  },
];
