import Head from 'next/head'

export default function Home() {
  return (
    <>
      {/*Head : Contain title, metadata, icon*/}
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Body : Yeah, It's body*/}
      <body>
        <p>hi</p>
      </body>
    </>
  );
}
