import Head from 'next/head'
import { useState } from "react"


export default function Home() {

  const [welcome, setWelcome] = useState([])
  async function fetchWelcome() {
    /* Wait for respond */
    const rWelcome = await fetch('/api/page/welcome')
    /* And then convert to json */
    const dWelcome = await rWelcome.json()
    setWelcome(dWelcome)
  }
  window.onload = fetchWelcome;
  return (
    <>
      {/*Head : Contain title, metadata, icon*/}
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Body : Yeah, It's body*/}
      <body>
        <div className="container">
          <article class="prose lg:prose-xl ml-8">
            {
              welcome.map(welcome => {
                return (
                  <div>
                    {welcome.text}
                  </div>
                )
              })
            }
            <h1></h1>
          </article>
        </div>
      </body>
    </>
  );
}
