import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      {/*Head : Contain title, metadata, icon*/}
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Body : Yeah, It's body*/}
      <body>
        <div className="container">
        <article class="prose lg:prose-xl">
  # head xd
  </article>
        </div>
      </body>
    </>
  )
}
